import React from 'react';
import ResumeViewer from './resume';
import CoverViewer from './cover';
import neon from './neon.svg';
import './App.css';
import { pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

const App = () => {
  return (
    <div className="App">
      <header className="App-header">
        <div className="tooltip">
          {/* <span className="tooltiptext">I hope I don't get sued for this logo</span> */}
          <div className="title"><div className=''><img src={neon} className="neon-logo" alt="neon" /></div><div className='me'> 🤝 &nbsp; <a href="https://www.linkedin.com/in/ojas-wadhwani-99a14315a/"> Ojas</a></div></div>
        </div>
        <div className="description">
          <p>
            Dear Hiring Team,
          </p>
          <p>
            I am submitting my application for the Fullstack Engineer (Growth Team) <a href="https://boards.greenhouse.io/neondatabase/jobs/5132407004">position</a> at Neon, a serverless Postgres solution.
          </p>
          <p>
            This app was made using my previous work in <b>Growth team</b> at <a href="https://hasura.io">Hasura</a>. Using <a href="https://vercel.com/integrations/hasura">Vercel-Hasura integration</a>, coupled with <a href="https://hasura.io/docs/latest/databases/postgres/neon/">Hasura-Neon integration</a>, I have crafted a comprehensive full stack application.
            It dynamically fetches PDF documents stored within a Google Cloud Storage bucket via links managed in a Neon Postgres database <span className="neon-db">(<b><u>db</u></b>)<span class="neon-tooltip">informed-hen-52_db_4334576</span></span> connected through Hasura.
            The frontend, hosted on Vercel, interacts with the GraphQL API generated by Hasura, utilizing <b>react-query</b> for data fetching and <b>react-pdf</b> for document display.
          </p>
          <p>Please find my resume and cover letter for the job application below.</p>
          <p>Warm regards. <div className="source"><a href="https://github.com/OjasWadhwani/neon-application">source code</a></div></p>

        </div>
        <div className='application'>
          <ResumeViewer />
          <CoverViewer />
        </div>
      </header >
    </div >
  );
};

export default App;
